from classes.exception.base_app_exception import BaseAppException

class ValidationException(BaseAppException):
    pass
